- name: Upload Semgrep Report to DefectDojo
  run: |
    curl -X POST \
      -F "file=@semgrep-report.json" \
      -F "product_name=Juice Shop AppSec" \
      -F "engagement_name=CI/CD Pipeline Scan" \
      -F "scan_type=Semgrep JSON Report" \
      -u "admin:admin" \
      http://localhost:8000/api/v2/import-scan/
